services:
  - type: web
    name: myntra-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
